Feature login
devhausleipzig/garden-share pull request #20
Opened 2022-04-12 11:51 UTC by inpatr

2022-04-12 12:15 UTC, dnmct requested changes
It's looks odd that the card for login and signup have different sizes.
I think it would look way nicer if they would be the same size.
also consider adding some space between the form and the boundaries of the card.

2022-04-12 14:37 UTC, inpatr commented on pages/login/index.tsx
> +                    type={"submit"}
removed all unnecessary curlies!

2022-04-12 14:38 UTC, inpatr commented
resized signup but with smaller logo:
<img width="806" alt="signup2" src="https://user-images.githubusercontent.com/97885124/162987735-1c13f622-ed93-418c-b90d-6bcab687a2ea.png">

okay like that or should we just make both forms way bigger?

2022-04-12 16:47 UTC, dnmct requested changes
It's better now.
The logo has different sizes on both pages though.
Also the form can still have more padding, the card still looks cramped

2022-04-13 07:45 UTC, inpatr commented
login:
<img width="1680" alt="login" src="https://user-images.githubusercontent.com/97885124/163125907-3b3481e0-c59f-4d03-878b-720f68b19e76.png">
signup:
<img width="1680" alt="signup" src="https://user-images.githubusercontent.com/97885124/163125956-919429b0-6b33-49b1-a60c-dae595ba44ee.png">

2022-04-13 08:16 UTC, dnmct approved these changes
👍🏻

2022-04-13 08:17 UTC, merged